### PR TITLE
there is a the read timeout exception.

### PR DESCRIPTION
**Pull request by Neisuz**
https://github.com/quarkusio/quarkus/issues/11076

### CODE REVIEW

**Comment by phillip-kruger** [comment]
Thanks !! I'll look at soon

**Comment by phillip-kruger** [comment]
Please add  `.idea/` to the gitigore

**Comment by Neisuz** [comment]
done it, i guess so

**Comment by phillip-kruger** [comment]
It's still showing 323 files changed, most from .idea

**Comment by Neisuz** [comment]
done it, everything is fine .

**Comment by phillip-kruger** [comment]
Thanks :) You an actually also add all .iml files as those are idea files. But at least I can look at it now...

**Comment by Neisuz** [comment]
i did my best :D ...

**Comment by phillip-kruger** [comment]
Hi @Neisuz . I manage to recreate the issue thanks to your PR. It's very weird ! Two things:
1) It does not seem like you need the undertow extension. Everything still work without it.
2) There is definitely an issue when you add undertow, for that we need someone like Stuart. I'll ping him again on the original issue. He is on PTO at the moment.

Why did you add the undertow extension ?

**Comment by Neisuz** [comment]
Hi, thank you so much. Here the thing, i've got more bigger project where i used Rest and undertow extensions, everything was fine. Then i have decided to add Graphql extension and all functions with POST,UPDATE where i get "inputstream" as parameter are broke.

**Pull request merged**
